easy_admin:
    user:
      name_property_path: 'username'
    site_name: 'AC-Architecture Admin'
    # edit:
    #     actions: ['-delete']
    design:
        assets:
            js:
                - 'https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=yq0h5mlf29y38s38t1vdx23xv0kv6tc5g5f6g7mo95cjwxv0'
        menu:
            - label: 'Pages'
              children:
                  - { label: "L'agence - Presentation", entity: 'Presentation', params: { action: 'edit', id: 1 } }
                  - { label: "L'agence - Equipe", entity: 'Equipe', params: { action: 'edit', id: 1 } }
                  - { label: "L'agence - Organisation", entity: 'Organisation', params: { action: 'edit', id: 1 } }
                  - { label: "Services", entity: 'Services', params: { action: 'edit', id: 1 } }
            - label: 'Réalisations'
              children:
                  - { label: "EHPAD", entity: 'EHPAD'}
                  - { label: "Logement Colectifs", entity: 'Collectif'}
                  - { label: "Logement Individuels", entity: 'Individuel'}
                  - { label: "Lieux Cultuels", entity: 'Cultuel'}
                  - { label: "Equipements", entity: 'Equipement'}
    entities:
        Presentation:
            class: App\Entity\Presentation
            form:
                fields:
                    - { property: 'contentHtml', label: "Contenu de la Page :" ,type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }
            disabled_actions: ['delete', 'list']
        Equipe:
            disabled_actions: ['delete', 'list']
            class: App\Entity\Equipe
            form:
                fields:
                    - { property: 'contentHtml', label: "Contenu de la Page :" ,type: 'textarea' }
                    - { property: 'equipe1File', label: "Membre n°1 Photo :", type: 'vich_image' }
                    - { property: 'equipe1Name', label: "Membre n°1 Nom :", type: 'text' }
                    - { property: 'equipe1Role', label: "Membre n°1 Rôle :", type: 'text' }
                    - { property: 'equipe1Role2', label: "Membre n°1 Rôle 2 :", type: 'text' }
                    - { property: 'equipe1Cv', label: "Membre n°1 CV :" ,type: 'textarea' }
                    - { property: 'equipe2File', label: "Membre n°2 Photo :", type: 'vich_image' }
                    - { property: 'equipe2Name', label: "Membre n°2 Nom :", type: 'text' }
                    - { property: 'equipe2Role', label: "Membre n°2 Rôle :", type: 'text' }
                    - { property: 'equipe2Role2', label: "Membre n°2 Rôle 2 :", type: 'text' }
                    - { property: 'equipe2Cv', label: "Membre n°2 CV :" ,type: 'textarea' }
                    - { property: 'equipe3File', label: "Membre n°3 Photo :", type: 'vich_image' }
                    - { property: 'equipe3Name', label: "Membre n°3 Nom :", type: 'text' }
                    - { property: 'equipe3Role', label: "Membre n°3 Rôle :", type: 'text' }
                    - { property: 'equipe3Role2', label: "Membre n°3 Rôle 2 :", type: 'text' }
                    - { property: 'equipe3Cv', label: "Membre n°3 CV :" ,type: 'textarea' }
                    - { property: 'equipe4File', label: "Membre n°4 Photo :", type: 'vich_image' }
                    - { property: 'equipe4Name', label: "Membre n°4 Nom :", type: 'text' }
                    - { property: 'equipe4Role', label: "Membre n°4 Rôle :", type: 'text' }
                    - { property: 'equipe4Role2', label: "Membre n°4 Rôle 2 :", type: 'text' }
                    - { property: 'equipe4Cv', label: "Membre n°4 CV :" ,type: 'textarea' }
                    - { property: 'equipe5File', label: "Membre n°5 Photo :", type: 'vich_image' }
                    - { property: 'equipe5Name', label: "Membre n°5 Nom :", type: 'text' }
                    - { property: 'equipe5Role', label: "Membre n°5 Rôle :", type: 'text' }
                    - { property: 'equipe5Role2', label: "Membre n°5 Rôle 2 :", type: 'text' }
                    - { property: 'equipe5Cv', label: "Membre n°5 CV :" ,type: 'textarea' }
                    - { property: 'equipe6File', label: "Membre n°6 Photo :", type: 'vich_image' }
                    - { property: 'equipe6Name', label: "Membre n°6 Nom :", type: 'text' }
                    - { property: 'equipe6Role', label: "Membre n°6 Rôle :", type: 'text' }
                    - { property: 'equipe6Role2', label: "Membre n°6 Rôle 2 :", type: 'text' }
                    - { property: 'equipe6Cv', label: "Membre n°6 CV :" ,type: 'textarea' }
                    - { property: 'equipe7File', label: "Membre n°7 Photo :", type: 'vich_image' }
                    - { property: 'equipe7Name', label: "Membre n°7 Nom :", type: 'text' }
                    - { property: 'equipe7Role', label: "Membre n°7 Rôle :", type: 'text' }
                    - { property: 'equipe7Role2', label: "Membre n°7 Rôle 2 :", type: 'text' }
                    - { property: 'equipe7Cv', label: "Membre n°7 CV :" ,type: 'textarea' }
        Organisation:
            disabled_actions: ['delete', 'list']
            class: App\Entity\Organisation
            form:
                fields:
                    - { property: 'contentHtml', label: "Contenu de la Page :" ,type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }
        Services:
            disabled_actions: ['delete', 'list']
            class: App\Entity\Services
            form:
                fields:
                    - { property: 'contentHtml', label: "Contenu de la Page :" ,type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }
        EHPAD:
            class: App\Entity\EHPAD
            form:
                fields:
                    - { property: 'title', label: "Titre de la réalisation :" ,type: 'text' }
                    - { property: 'thumbnailFile', label: "Miniature :" ,type: 'vich_image' }
                    - { property: 'contentRightHtml', label: "Contenu à droite :" ,type: 'textarea' }
                    - { property: 'contentBottomHtml', label: "Contenu en bas :" ,type: 'textarea' }
                    - { property: 'image1File', label: "Image n°1:", type: 'vich_image' }
                    - { property: 'image2File', label: "Image n°2:", type: 'vich_image' }
                    - { property: 'image3File', label: "Image n°3:", type: 'vich_image' }
                    - { property: 'image4File', label: "Image n°4:", type: 'vich_image' }
                    - { property: 'image5File', label: "Image n°5:", type: 'vich_image' }
                    - { property: 'projectFileFile', label: "Fiche projet:", type: 'vich_file' }
            list:
                fields:
                    - { property: 'id'}
                    - { property: 'thumbnail', type: 'image', label: 'Image', base_path: '%app.path.images%' }
                    - { property: 'title', label: 'Titre' }
        Collectif:
              class: App\Entity\Collectif
              form:
                  fields:
                      - { property: 'title', label: "Titre de la réalisation :" ,type: 'text' }
                      - { property: 'thumbnailFile', label: "Miniature :" ,type: 'vich_image' }
                      - { property: 'headerImgFile', label: "Image d'entête :", type: 'vich_image' }
                      - { property: 'contentHtml', label: "Contenu de la page :" ,type: 'textarea' }
                      - { property: 'sideImg1File', label: "Image n°1:", type: 'vich_image' }
                      - { property: 'sideImg2File', label: "Image n°2:", type: 'vich_image' }
                      - { property: 'sideImg3File', label: "Image n°3:", type: 'vich_image' }
                      - { property: 'projectFileFile', label: "Fiche projet:", type: 'vich_file' }
        Individuel:
            class: App\Entity\Individuel
            form:
                fields:
                    - { property: 'title', label: "Titre de la réalisation :" ,type: 'text' }
                    - { property: 'thumbnailFile', label: "Miniature :" ,type: 'vich_image' }
                    - { property: 'headerImgFile', label: "Image d'entête :", type: 'vich_image' }
                    - { property: 'contentHtml', label: "Contenu de la page :" ,type: 'textarea' }
                    - { property: 'sideImg1File', label: "Image n°1:", type: 'vich_image' }
                    - { property: 'sideImg2File', label: "Image n°2:", type: 'vich_image' }
                    - { property: 'sideImg3File', label: "Image n°3:", type: 'vich_image' }
                    - { property: 'projectFileFile', label: "Fiche projet:", type: 'vich_file' }
        Cultuel:
            class: App\Entity\Cultuel
            form:
                fields:
                    - { property: 'title', label: "Titre de la réalisation :" ,type: 'text' }
                    - { property: 'thumbnailFile', label: "Miniature :" ,type: 'vich_image' }
                    - { property: 'headerImgFile', label: "Image d'entête :", type: 'vich_image' }
                    - { property: 'contentHtml', label: "Contenu de la page :" ,type: 'textarea' }
                    - { property: 'sideImg1File', label: "Image n°1:", type: 'vich_image' }
                    - { property: 'sideImg2File', label: "Image n°2:", type: 'vich_image' }
                    - { property: 'sideImg3File', label: "Image n°3:", type: 'vich_image' }
                    - { property: 'projectFileFile', label: "Fiche projet:", type: 'vich_file' }
        Equipement:
            class: App\Entity\Equipement
            form:
                fields:
                    - { property: 'title', label: "Titre de la réalisation :" ,type: 'text' }
                    - { property: 'thumbnailFile', label: "Miniature :" ,type: 'vich_image' }
                    - { property: 'headerImgFile', label: "Image d'entête :", type: 'vich_image' }
                    - { property: 'contentHtml', label: "Contenu de la page :" ,type: 'textarea' }
                    - { property: 'sideImg1File', label: "Image n°1:", type: 'vich_image' }
                    - { property: 'sideImg2File', label: "Image n°2:", type: 'vich_image' }
                    - { property: 'sideImg3File', label: "Image n°3:", type: 'vich_image' }
                    - { property: 'projectFileFile', label: "Fiche projet:", type: 'vich_file' }
