easy_admin:
    site_name: 'AC-Architecture Admin'
    design:
        assets:
            js:
                - 'https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=yq0h5mlf29y38s38t1vdx23xv0kv6tc5g5f6g7mo95cjwxv0'
        menu:
            - label: 'Pages'
              children:
                  - { label: "L'agence - Presentation", entity: 'Presentation', params: { action: 'edit', id: 1 } }
                  - { label: "L'agence - Equipe", entity: 'Equipe', params: { action: 'edit', id: 1 } }
                  - { label: "L'agence - Organisation", entity: 'Organisation', params: { action: 'edit', id: 1 } }
                  - { label: "Services", entity: 'Services', params: { action: 'edit', id: 1 } }
            - label: 'Réalisations'
              children:
                  - { label: "EHPAD", entity: 'EHPAD'}
    entities:
        Presentation:
            class: App\Entity\Presentation
            form:
                fields:
                    - { property: 'contentHtml', label: "Contenu de la Page :" ,type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }
        Equipe:
            class: App\Entity\Equipe
            form:
                fields:
                    - { property: 'contentHtml', label: "Contenu de la Page :" ,type: 'textarea' }
                    - { property: 'equipe1File', label: "Membre n°1 Photo :", type: 'vich_image' }
                    - { property: 'equipe1Cv', label: "Membre n°1 CV :" ,type: 'textarea' }
                    - { property: 'equipe2File', label: "Membre n°2 Photo :", type: 'vich_image' }
                    - { property: 'equipe2Cv', label: "Membre n°2 CV :" ,type: 'textarea' }
                    - { property: 'equipe3File', label: "Membre n°3 Photo :", type: 'vich_image' }
                    - { property: 'equipe3Cv', label: "Membre n°3 CV :" ,type: 'textarea' }
                    - { property: 'equipe4File', label: "Membre n°4 Photo :", type: 'vich_image' }
                    - { property: 'equipe4Cv', label: "Membre n°4 CV :" ,type: 'textarea' }
                    - { property: 'equipe5File', label: "Membre n°5 Photo :", type: 'vich_image' }
                    - { property: 'equipe5Cv', label: "Membre n°5 CV :" ,type: 'textarea' }
                    - { property: 'equipe6File', label: "Membre n°6 Photo :", type: 'vich_image' }
                    - { property: 'equipe6Cv', label: "Membre n°6 CV :" ,type: 'textarea' }
                    - { property: 'equipe7File', label: "Membre n°7 Photo :", type: 'vich_image' }
                    - { property: 'equipe7Cv', label: "Membre n°7 CV :" ,type: 'textarea' }
        Organisation:
            class: App\Entity\Organisation
            form:
                fields:
                    - { property: 'contentHtml', label: "Contenu de la Page :" ,type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }
        Services:
            class: App\Entity\Services
            form:
                fields:
                    - { property: 'contentHtml', label: "Contenu de la Page :" ,type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }
        EHPAD:
            class: App\Entity\EHPAD
            form:
                fields:
                    - { property: 'title', label: "Titre de la réalisation :" ,type: 'text' }
                    - { property: 'thumbnailFile', label: "Miniature :" ,type: 'vich_image' }
                    - { property: 'headerImgFile', label: "Image d'entête :", type: 'vich_image' }
                    - { property: 'contentHtml', label: "Contenu de la page :" ,type: 'textarea' }
                    - { property: 'sideImg1File', label: "Image n°1:", type: 'vich_image' }
                    - { property: 'sideImg2File', label: "Image n°2:", type: 'vich_image' }
                    - { property: 'sideImg3File', label: "Image n°3:", type: 'vich_image' }
                    - { property: 'projectFileFile', label: "Fiche projet:", type: 'vich_file' }
