vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix:         '%app.path.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
        fiches:
            uri_prefix:         '%app.path.fiches%'
            upload_destination: '%kernel.project_dir%/public%app.path.fiches%'
        schema:
            uri_prefix:         '%app.path.schema%'
            upload_destination: '%kernel.project_dir%/public%app.path.schema%'
        arrete:
            uri_prefix:         '%app.path.arrete%'
            upload_destination: '%kernel.project_dir%/public%app.path.arrete%'